package org.example.Listener;

import org.example.domein.Account;
import org.example.domein.Data;
import org.example.domein.Material;
import org.example.persistance.PersistenceManager;

import javax.servlet.ServletContextEvent;
import javax.servlet.ServletContextListener;
import javax.servlet.annotation.WebListener;
import java.io.IOException;
import java.time.Duration;

import org.example.domein.Character;
import reactor.core.scheduler.Schedulers;
import reactor.netty.http.HttpResources;

@WebListener
public class MyServletContextListener implements ServletContextListener {

    public void contextInitialized(ServletContextEvent sce) {

        System.out.println("System is booting");

        try {
            PersistenceManager.loadDataFromAzure();

            // lazy character
            Character sherb = new Character("Sherb", "Male","Lazy","Goat", "January 18th", "Forty winks is never enough." , "Sherb (レム, Remu) is a lazy goat villager introduced in New Horizons. His name comes from sherbet, a type of ice cream. His Japanese name, Rem, may be a reference to REM sleep, further supported by his apparent love of sleeping, and his favorite song being Hypno K.K. \n "+ "\n" +" He has the nature hobby.");
            sherb.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/d/d6/Sherb.png/revision/latest?cb=20200406180522");
            Character hornsby = new Character("Hornsby", "Male", "Lazy", "Rhino", "March 20th", "You can't hit a mosquito with a horseshoe.", "Hornsby (みつお, Mitsuo) is a lazy rhino villager from the Animal Crossing series. His name is a play on the horn on his head. His picture quote in New Leaf seems to be a reference to his e-reader card profile. Hornsby was first seen in the GCN games, and did not appear in future iterations until the Welcome amiibo update in New Leaf. He was, however, found in the data for Happy Home Designer, but unlike many other unused villagers, he has no icon and only textures for him exist in the game's code.");
            hornsby.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/9/95/Hornsby_NH.png/revision/latest/scale-to-width-down/333?cb=20200312014627");
            Character bob = new Character("Bob", "Male", "Lazy", "Cat", "January 1st", "I'm a cat. Chillin' is in my blood, man.", "Bob (ニコバン, Nikoban) is a lazy cat villager who has appeared in every game of the Animal Crossing series. His name is most likely based off the bobcat. His initial phrase, \"pthhhpth,\" may be a reference to the sound a cat makes when coughing up a hairball (this is further supported by the information on the e-Reader card which indicates he tends to spit often while speaking). His picture phrase in New Leaf is a feline spin on the memetic phrase, \"You only live once.\" \n " + "\n" + " He has the play hobby.");
            bob.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/b/be/175px-Bob_NLa.png/revision/latest?cb=20200413200623");
            Character beau = new Character("Beau", "Male", "Lazy", "Deer", "April 5th", "You snooze, you lose.", "Beau (ぺーター, Pētā, Peter) is a lazy deer villager in the Animal Crossing series. His name is a masculine word which means 'beautiful' or 'handsome' in French, and is pronounced 'bow'. His initial phrase refers to a salt block, which some people use to attract deer. Beau is very similar to an antelope, which are deer-like animals that are common in Africa and Eurasia.\n" + "\n" + "He is featured on the cover of Mr. K.K. and he has the nature hobby.");
            beau.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/d/d4/Beau_NH.png/revision/latest/scale-to-width-down/290?cb=20200501231808");
            Character bones = new Character("Bones", "Male", "Lazy", "Dog", "August 4th", "Fossils are so HUGE and AWESOME! I hope I grow up to be a fossil someday", "Bones (トミ, Tomi, Tommy) is a lazy dog villager in the Animal Crossing series. He has appeared in every game to date. His name probably originated from the fact that dogs famously love to chew bones, as well as the phrase \"lazy bones\". \n " + "\n" + "He has the play hobby.");
            bones.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/8/8b/HDBonesNL.png/revision/latest?cb=20200618181914");
            Character boomer = new Character("Boomer", "Male", "Lazy", "Penguin", "February 7th", "Flying is believing.", "Boomer (ショーイ, Shōi) is a lazy penguin villager who first appears in Animal Forest+ as an islander. He was absent in Wild World, but reappears in City Folk. His name most likely comes from a character of the same name in Battlestar Galactica, who was also a pilot; more evidence towards this is how his room is space-themed in New Leaf. His initial catchphrase \"human\", is another reference to Battlestar Galactica, in which Boomer is a non-human character living among humans. \n " + "\n" + "He has the fitness hobby.");
            boomer.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/f/f5/HDBoomerNL.png/revision/latest/scale-to-width-down/350?cb=20200618182022");
            Character kidd = new Character("Kidd", "Male", "Lazy", "Goat", "June 28th", "Be yourself - everyone else is already taken.", "Kidd (やさお, Yasao) is a smug goat from the Animal Crossing series. His first appearance was in Animal Forest e+, where he was a lazy islander. He later reappears in New Leaf, as a smug villager. His name comes from the offspring of goats, known as \"kids\". \n " + "He has the education hobby.");
            kidd.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/c/c5/Kidd_HHD.png/revision/latest?cb=20161213013210");
            Character cube = new Character("Cube", "Male", "Lazy", "Penguin", "January 29th", "Sometimes you gotta learn to chill.", "Cube (ビス, Bisu) is a lazy penguin villager in the Animal Crossing series who first appears in Animal Forest. He is possibly named after the GameCube, supported by the fact that his starting outfit is the GC logo Shirt. However as he appeared in Animal Forest on the Nintendo 64, his name is more likely based on an ice cube. His initial phrase, \"d-d-dude,\" references cold, as words are usually a stutter in cold temperatures. It is similar to Gwen's, Aurora's and Roald's. \n " + "\n" + "He has the play hobby.");
            cube.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/1/10/Cube_NH.png/revision/latest?cb=20200226233057");
            Character deli = new Character("Deli", "Male", "Lazy", "Monkey", "May 24th", "Righty tighty, lefty loosey.", "Deli (デリー, Derī, Delhi) is a lazy monkey villager who first appeared in New Leaf. His Japanese name is possibly a reference to the Monkey-man of Delhi and his English one probably to the words 'delicacy' or 'delicatessen'. His New Leaf picture quote could relate to a monkey wrench with the rhyme teaching which way to turn the wrench to loosen or tighten a screw or bolt.\n" + "\n" + "He has the nature hobby.");
            deli.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/a/a1/Deli_HD.png/revision/latest/scale-to-width-down/350?cb=20180518164618");

            //normal character
            Character lilly = new Character("Lilly", "Female", "Normal", "Frog", "February 4th", "Don't jump to conclusions!", "Lily (レイニー Reinī, Rainy) is a frog villager in the Animal Crossing series with a normal personality. Her name may be a reference to lily pads. Her initial phrase in Animal Crossing is a play on the words \"toad\" and \"totally,\" which make \"toadally.\" She has appeared in every game in the Animal Crossing series so far. \n " + "\n" + "She has the education hobby.");
            lilly.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/e/e8/Lili_%28New_Horizons%29.png/revision/latest/scale-to-width-down/340?cb=20200221074157&path-prefix=es");
            Character melba = new Character("Melba", "Female", "Normal", "Koala", "April 12th", "I just don't get it. Why would you come all this way just to sit in a dark theater, toasty", "Melba (アデレード, Aderēdo, Adelaide) is a normal koala villager in the Animal Crossing series. She first appeared in Wild World, and subsequently in City Folk and New Leaf. Melba's name may relate to the Australian city of Melbourne, also the Australian opera singer Dame Nelly Melba, who also represents her own ice-cream and Melba toast, which her phrase, \"toasty,\" is a reference to: a dry, crisp, and thinly-sliced piece of toast that originated and is popular in Australia, where koalas are also from. Another theory is that the phrase \"toasty\" references Australia being a constantly warm country. Her Japanese name refers to the Australian city of the same name. She replaces another female koala in the original games (with a different personality) called Huggy. \n " + "\n" + "She has the education hobby.");
            melba.setPicture("https://dodo.ac/np/images/thumb/4/43/Melba_NH.png/175px-Melba_NH.png");
            Character kiki = new Character("Kiki", "Female", "Normal", "Cat","October 8th", "Hang in there, kiddo.", "Kiki (キャビア, Kyabia, Caviar) is a normal cat villager which has appeared in every Animal Crossing series game. Her name may come from Hayao Miyazaki's Kiki's Delivery Service, an anime film about a young witch-in-training named Kiki who has a black cat. Her Japanese name refers to Caviar, a fish egg delicacy that cats love. She has the education hobby.\n" + "Kiki may be a reference to the black cat, or it may come from the sound produced when saying \"kittykitty\" fast. Her quote on her picture in Wild World probably comes from the popular motivational poster of a cat hanging from a tree and saying \"Hang in there.\". \n " + "\n" + " Her New Leaf picture quote is akin to K.K. Slider's.");
            kiki.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/4/4b/Kiki_NL.png/revision/latest/scale-to-width-down/247?cb=20130708021703");
            Character flurry = new Character("Flurry", "Female", "Normal", "Hamster", "January 30th", "My bed is so soft and warm! After a full night's sleep, I always wake up refreshed and ready to go.", "Flurry (ゆきみ Yukimi) is a normal hamster villager who first appeared in New Leaf. Her Japanese and English names both have to do with snow, Yukimi meaning \"snow viewing\" and Flurry meaning a light snowfall. Her Spanish name, however, means rain. In addition, her Italian name translates to \"meringue\" which is a light egg-white-based dessert. \n " + "She has the nature hobby.");
            flurry.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/3/30/Flurry_HD.png/revision/latest/scale-to-width-down/350?cb=20180405153933");
            Character midge = new Character("Midge", "Female", "Normal", "Bird", "March 12th", "When the world gets cold, just fly south.", "Midge (うずまき, Uzumaki) is a normal bird villager who has appeared in every game except Wild World. Her name might be a reference to the insect midge which many birds feed on. Her Japanese name means Spiral, referencing the spiral design on her cheeks. Her catchphrase, \"tweedledee,\" is a reference to the chirping of some smaller species of birds. Her quote is a reference to the migration of birds during the winter. She has the education hobby.\n" + "\n" + "She appears on the album cover for K.K. Aria and K.K. Marathon.");
            midge.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/1/15/Midge_NewLeaf_Official.png/revision/latest/scale-to-width-down/301?cb=20130721195051");
            Character gala = new Character("Gala", "Female", "Normal", "Pig", "March 5th", "It's fun to dress up and look so cute on occasion!" , "Gala (ためこ Tameko) is a normal pig villager in the Animal Crossing series who makes her first appearance in City Folk. Her name may refer to a type of apples, Gala Apples, or it may also refer to \"Gala Pork Pie.\" Her catchphrase references the snorting sounds that most pigs make. She has the education hobby.\n" + "\n" + "She appears on the cover of Señor K.K.");
            gala.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/f/fb/Gala_NewLeaf_Official.png/revision/latest/scale-to-width-down/282?cb=20130721190601");
            Character skye = new Character("Skye", "Female", "Normal", "Wolf", "March 24th", "Just a moment ago, I saw a cloud that really reminded me of gingerbread.", "Skye (リリィ, Rirī, Lily) is a normal wolf villager who first appeared in New Leaf. She is the only wolf with the normal personality.\n" + "Her name derives from her sky-inspired appearance, while her initial phrase references mail sent via aircraft. Skye's Japanese name, Lily, refers to the flower of the same name, which are often a white color similar to Skye's highlight colours.\n" + "\n" + "Her picture quote is similar to that of the peppy cub villager, Bluebear. She appears on the album cover for Café K.K. \n " + "\n" + "She has the music hobby.");
            skye.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/a/aa/NH-icon-Skye_00.png/revision/latest/scale-to-width-down/248?cb=20200224182217");
            Character bertha = new Character("Bertha", "Female", "Normal", "Hippo", "April 25th", "The best part of spring is the picnics!", "Bertha (あんこ, Anko) is a normal hippo villager from the Animal Crossing series. Her name may refer to the name \"Big Bertha\", a name given to a range of large cannons. Her Japanese name means \"bean paste\". Her catchphrase could be related to the sound of splashing in water, as hippos live with areas with water. She has the same initial phrase as Zucker.\n" + "\n" + "She has the education hobby.");
            bertha.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/0/0c/BerthaNH.png/revision/latest/scale-to-width-down/350?cb=20200618181301");

            //sisterly
            Character cherry = new Character("Cherry", "Female","Sisterly", "Dog", "May 11th", "One dog barks at something, the rest bark at him.", "Cherry (ハンナ, Hanna) is a sisterly villager in New Leaf. Her name may come from her fur color, which is a darker pink tone, resembling a cherry.\n"+ "\n" + "She has a music hobby.");
            cherry.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/3/3e/Cherry_NH.png/revision/latest/scale-to-width-down/300?cb=20200524035737");
            Character hazel = new Character("Hazel", "Female","Sisterly","Squirrel","August 30th","Never say never!", "Hazel (アイリス, Airisu, Iris) is a sisterly squirrel villager who first appeared in New Leaf. Her name comes from hazelnut, a type of nut. A certain villager already had the name of Hazel, but due to Nintendo of America's localization error, this villager was given the name of Hazel. That villager was then renamed to Sally due to yet another localization error on Nintendo of America's part. Not only that, but the new name given, Sally, was already owned by another villager too, who was renamed Cally. Her initial phrase is a reference to her uni-brow, hinting that she is proud of it.\n " + "\n" + "She has the play hobby.");
            hazel.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/1/17/Hazel_NH.png/revision/latest/scale-to-width-down/350?cb=20200309012107");
            Character katt = new Character("Katt", "Female", "Sisterly", "Cat", "April 27th", "MeowMEOWmeow!", "Katt (ちょい, Choi) is a sisterly cat villager who first appeared in New Leaf. Her name means 'cat' in Swedish and Norwegian, and her catchphrase refers to the word \"pretty\"; She is the only sisterly cat so far. \n " + " She appears on the album cover for Spring Blossoms. \n" + "\n" + "She has the music hobby.");
            katt.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/6/68/Katt_HD.png/revision/latest/scale-to-width-down/350?cb=20180404115701");
            Character phoebe = new Character("Phoebe", "Female", "Sisterly", "Ostrich", "April 22nd", "You know, I really have no idea what you do all day! Are you super sly, or am I just not paying attention?", "Phoebe (ヒノコ, Hinoko) is a sisterly ostrich villager who first appears in New Leaf And New Horizons. Both Phoebe's English and Japanese names are plays on the mythical phoenix--one of the Japanese words for which is hi-no-tori, roughly translating to \"firebird\". Her initial phrase is most likely a reference to the sparks that come from a fire. \n " + "\n" + "She appears on the album covers for K.K. Parade and K.K. Salsa. \n " + "\n" + "She has the fitness hobby.");
            phoebe.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/5/50/Phoebe_NH.png/revision/latest/scale-to-width-down/242?cb=20200308185133");
            Character ursula = new Character("Ursula", "Female", "Sisterly", "Bear", "January 16th", "Do you have candy for me? If you do, you best hand it over, groomph!", "Ursala (ネーヤ, Neeya) is a sisterly (formerly snooty) bear villager from the Animal Crossing series, originally exclusive to GCN games. She was found in the data for HHD. Her name comes from the Latin word \"ursa\", which means \"bear\", and the female name, \"Ursula.\"\n" + "Ursala returned to the series in New Leaf, as part of the Welcome amiibo update. By scanning amiibo cards, this villager can be met via the campground and invited to the town.\n" + "\n" + "She has the music hobby.");
            ursula.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/b/bd/Ursala_HD.png/revision/latest/scale-to-width-down/350?cb=20180518170342");

            //snooty
            Character ankha = new Character("Ankha", "Female", "Snooty", "Cat", "September 22nd", "You again? You just can't seem to stay away from ME!", "Ankha (ナイル, Nairu, Nile) is a snooty cat villager in the Animal Crossing series, appearing in every game except Animal Forest and Wild World. She reappears in City Folk as well as New Leaf. In Animal Forest+, Animal Crossing, and in Animal Forest e+, she is an Islander. Her name is based on the ankh, which is the Egyptian hieroglyphic character that reads \"life.\" Alternatively, her name could come from the famous Egyptian pharaoh Tutankhamun, whose tomb inspired Ankha's hair colors and snake hairpiece. In New Leaf, her picture quote is a reference to the play \"The Merchant of Venice\" as Bassanio says the same about the lead casket.\n" + "Her Japanese name is \"Nile,\" which refers to the African river that many Egyptians settled on. Her German name, \"Kleo\" is short for \"Kleopatra,\" the German version of Cleopatra, the famous Egyptian queen. As an islander in Animal Crossing, Ankha loves cherries and is allergic to apples.\n" + "\n" + "She has the nature hobby.");
            ankha.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/7/7e/Ankha_NLa.png/revision/latest?cb=20200413172251");
            Character diana = new Character("Diana", "Female", "Snooty", "Deer", "January 4th", "Don't look at me like that when I'm shopping! Even a fashion maven needs basic goods.", "Diana (ナタリー Natarī, Natalie) is a snooty deer villager who appears in New Leaf. She’s also the only snooty deer. Her name likely stems from Diana, the Roman goddess of the hunt, whose symbol was a deer. Her Spanish name Bambina means \"girl\" in Italian. It also bears a resemblance to \"Bambi\", a movie produced by Disney which features a deer fawn by the same name. Her initial phrase \"no doy\" is a variant of \"no duh\", a rather snooty phrase that is uttered to indicate that something said is quite blatantly obvious. \n" + "\n" + "She has the education hobby.");
            diana.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/8/84/31a901eed448f9ee30fc1af858e29be5_clipped_rev_2.png/revision/latest?cb=20161008150800");
            Character claudia = new Character("Claudia", "Female", "Snooty", "Tiger", "November 22nd", "It looked chewy, I guess, but it certainly WASN'T fruit!", "Claudia (マリリン, Maririn, Marilyn) is a snooty tiger villager who first appeared in New Leaf. Her Japanese name is most likely a reference to Marilyn Monroe, while her English name a pun on \"claw\". Her initial catchphrase is used commonly in movies or television shows and dramas involving preppy girls and snobby girls. It is similar to the one of Petunia. \n " + "\n" + "She has the music hobby.");
            claudia.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/d/d6/Claudia_NH.png/revision/latest/scale-to-width-down/283?cb=20200308194357");
            Character freya = new Character("Freya", "Female", "Snooty", "Wolf", "December 14th", "Having lots of hair is a big responsibility. Like owning a pet that sits on your head.", "Freya (ツンドラ, Tsundora, Tundra) is a snooty wolf villager from the Animal Crossing series. Her name comes from the Norse goddess of beauty, Freyja. Her Japanese name is the Japanese word for \"tundra\". Her catchphrase, \"uff da\", is a Norwegian exclamation that is an equivalent of the English \"Oh my\", \"That's too bad\", or \"Oh no\". It can be used to express concern. Freya was absent from Wild World, but reappeared in the subsequent games. She was the only female wolf until Animal Forest e+, where Vivian was introduced.\n" + "\n" + "She has the fashion hobby.");
            freya.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/5/50/NH-icon-Freya_00.png/revision/latest/scale-to-width-down/248?cb=20200224182111");
            Character velma = new Character("Velma", "Female", "Snooty", "Goat", "January 14th", "Work smarter, not harder.", "Velma (ピティエ, Pithie) is a snooty goat villager from the Animal Crossing series. Her catchphrase comes from the sound goats make.\n" + "\n" + "She is featured on the cover of K.K. Étude and she has the education hobby.");
            velma.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/8/8c/Velma_high_quality.png/revision/latest?cb=20200518173242");

            //cranky
            Character admiral = new Character("Admiral", "Male", "Cranky", "Bird", "January 27th", "Hmm, it's still anyone's game! It all up in the air at this point!", "Admiral is a cranky bird villager in the Animal Crossing series. He was originally exclusive to the GCN games. His name and initial quote are both sailing terms - admiral being a title given to the supreme commander of a ship, and \"aye aye\" is a phrase of affirmation. His name may also be a pun/reference to the famous naval officer and explorer, Admiral Byrd. His Japanese name means \"stubborn\".\n" + "\n" + "Admiral returned to the series in New Leaf, as part of the Welcome amiibo update. By scanning amiibo cards, this villager can be met via the campground and invited to the town.\n" + "\n" + "He has the nature hobby.");
            admiral.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/0/07/Admiral_HD.png/revision/latest/scale-to-width-down/350?cb=20180518160412");
            Character apollo = new Character("Apollo", "Male", "Cranky", "Eagle", "July 4th", "I'm not bald! I've just got fine feathers, that's all!", "Apollo (アポロ, Aporo) is a cranky eagle villager in the Animal Crossing series. He also appears in Dōbutsu no Mori as a minor character. Apollo is a bald eagle, specifically, the national bird of the United States of America, hence his July 4 birthday (Independence Day in the United States). He has the music hobby.\n" + "Apollo's name is probably a reference to Apollo 11, the first manned mission to land on the moon. Its lunar module, LM-5, used the callsign \"Eagle\", and a bald eagle also appears on the mission patch. His name is all the more appropriate considering the rather arrogant personality of the Greek god Apollo (as well as many other deities of ancient mythology).\n" + "\n" + "He appears on the album cover for Soulful K.K.");
            apollo.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/0/0c/NH-Apollo-Render.png/revision/latest/scale-to-width-down/350?cb=20200202215708");
            Character butch = new Character("Butch", "Male", "Cranky", "Dog", "November 1st", "A house without either a cat or a dog is a sad house indeed.", "Butch (ジョン, Jon, John) is a cranky dog villager in the Animal Crossing series. His name reflects on the cartoon name given to dogs, usually meaning muscular in appearance. Butch's rottweiler appearance may also relate to his name as they too appear masculine and muscular. His initial phrase, \"ROOOOOWF\", is a slight adjustment on the spelling of the common onomatopoeic words \"woof\" and \"ruff\". He is the first dog with a cranky personality. His Wild World picture quote is also exactly the same as Curt's picture quote. He has appeared in every game so far, including Pocket Camp.\n" + "\n" + "He is featured on the cover of K.K. Country and he has the music hobby.");
            butch.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/d/d2/Butch_-_Animal_Crossing_New_Leaf.png/revision/latest/scale-to-width-down/300?cb=20130708032928");
            Character chief = new Character("Chief", "Male", "Cranky", "Wolf", "December 19th", "I wonder if now is the best time to plant some dirt on someone.", "Chief (チーフ, Chīfu, Chief) is a cranky wolf villager that appears in all Animal Crossing games. His initial phrase, \"harrumph,\" is a sign of boredom or annoyance, which is consistent with his personality as a cranky villager. His name may be a reference to the leader of a wolf pack; sometimes called the chief.\n " + "He has the music hobby.");
            chief.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/e/e2/NH-icon-Chief_00.png/revision/latest/scale-to-width-down/248?cb=20200224180941");
            Character croque = new Character("Croque", "Male", "Cranky", "Frog", "July 18th", "Hey, you smell that fresh air? Yeah, you should savor that for as long as possible. No, I mean it. I had tacos for lunch. So enjoy the fresh air while you can.", "Croque (タイシ, Taishi) is a cranky frog villager who first appeared in New Leaf. His name is derived from the onomatopoeia \"croak\", which is a noise commonly thought to be made by a frog. He has the nature hobby.\n" + "Croque's apperance is based on Daruma-Taishi or Bodhidharma, an Indian monk born the prince of a country in southern India in the mid-5th Century. Bodhidharma is also the inspiration for the traditional Daruma dolls in Japanese culture, represented in game as the Dharma Set.");
            croque.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/0/05/Croque_HHD.png/revision/latest?cb=20161013031016");
            Character curt = new Character("Curt", "Male", "Cranky", "Bear", "Jult 1st", "I'm watching you!", "Curt (ガンテツ, Gantetsu) is a cranky bear villager in the Animal Crossing series. To be \"curt\" is to be impolitely brief, hence his name. His Wild World picture quote is also very similar to Chow's picture quote, both picture quotes telling the player that they are watching them, Butch's Wild World picture quote is exactly the same. His initial catchphrase may be a reference to his athletic motif in which it emulates the stereotypical language of a sports jock.\n" + "\n" + "He appears on the album covers for K.K. Dixie and K.K. Country.\n" + "\n" + "He has the nature hobby.");
            curt.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/f/f1/Nhcurt.png/revision/latest?cb=20200223062124");

            //smug
            Character beardo = new Character("Beardo", "Male", "Smug", "Bear", "September 27th", "I thought I had a slight fever from being in love, but it's gotten worse...", "Beardo (ベアード, Beādo) is a smug bear villager in the Animal Crossing series. His Japanese name comes from the type of facial hair, and could also be a pun on the word bear (Beard).\n" + "\n" + " He has the education hobby.");
            beardo.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/f/f9/Beardo_HHD.png/revision/latest?cb=20160624003458");
            Character colton = new Character("Colton", "Male", "Smug", "Horse", "May 22nd", "Make hay while the sun shines.", "Colton (アンソニー, Ansonī, Anthony) is a smug horse villager in the Animal Crossing series. His English name comes from the word colt, a young male horse.\n" + "\n" + "He is featured on the cover of Café K.K. and he has the nature hobby.");
            colton.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/f/f7/Colton_HD.png/revision/latest/scale-to-width-down/350?cb=20180405151848");
            Character eugene = new Character("Eugene", "Male", "Smug", "Koala", "October 26th", "Imitation is the sincerest form of flattery.", "Eugene (ロッキー, Rokkī, Rocky) is a smug koala villager in the Animal Crossing series. His name refers to the plant that koalas are known to love eating: eucalyptus. His catchphrase is a reference to his smug personality.\n" + "\n" + "He is featured on the cover of K.K. Ska and he has the music hobby.");
            eugene.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/9/93/Eugene_HHD.png/revision/latest?cb=20160624003222");
            Character graham = new Character("Graham", "Male", "Smug", "Hamster", "June 20th", "Knowledge is power.", "Graham (グラハム, Gurahamu, Graham) is a smug hamster villager who first appeared in New Leaf. His name could be based on the famous scientist Alexander Graham Bell, as well as a pun on his species, hamster. His catchphrase and picture quote could be a reference to the fact that he looks quite smart. His Spanish name is a pun on the verb \"roer\" which means \"to gnaw\" and is often associated with rodents (known in Spanish as \"roedores\") such as hamsters.\n" + "\n" + "He has the education hobby.");
            graham.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/5/54/Graham_HHD.png/revision/latest?cb=20161013033113");
            Character pietro = new Character("Pietro", "Male", "Smug", "Sheep", "April 19th", "Be the class clown.", "Pietro (ジュペッティ, Jupetti) is a smug sheep villager in the Animal Crossing series. His name is Italian and may be a play on Piero (ピエロ), the Japanese loanword for clown, or the french Pierrot.\n" + "\n" +"He has the music hobby.");
            pietro.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/f/fb/Pietro_NH.png/revision/latest/scale-to-width-down/342?cb=20200317165840");

            //peppy
            Character agent_s = new Character("Agent S", "Female", "Peppy", "Squirrel", "July 2nd", "I'm gonna, like, save the world!", "Agent S (2ごう, Ni Gō, #2) is a peppy squirrel villager from the Animal Crossing series. She was introduced in the 2003 Japanese exclusive Animal Forest e+, and reappeared in later games in the series. The \"S\" in her name most likely refers to her species, giving her the full title of Agent Squirrel. It is also possible that the \"S\" stands for sidekick, supporting the theory that she is Kid Cat's sidekick, also supported by her catchphrase and Japanese name.\n" + "\n" + "She has the fitness hobby.");
            agent_s.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/a/a7/Agent_S_NH.png/revision/latest?cb=20200608222107");
            Character apple = new Character("Apple", "Female", "Peppy", "Hamster", "September 24th", "Maybe I should dress up like a beautiful butterfly tomorrow, so someone will try to catch me!", "Apple (アップル, Appuru, Apple) is a peppy hamster villager in the Animal Crossing series. Her name comes from her red fur. Her catchphrase is a reference to the term \"apple-cheeked\", which is used to describe someone with round, rosy cheeks, which Apple has. It may also refer to the cheeks of a hamster, which are able to store large amounts of food at one time.\n" + "\n" + "She is featured on the cover of K.K. Gumbo and she has the play hobby.");
            apple.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/4/44/Apple_Villager.png/revision/latest?cb=20160504222447");
            Character bubbles = new Character("Bubbles", "Female", "Peppy", "Hippo", "September 18th", "Good afternoon! Still good, hipster?", "Bubbles (チャコ, Chako) is a peppy hippo villager in the Animal Crossing series. She has appeared in the GCN games and more recently in New Leaf. Bubbles's name may come from hippos' behavior of blowing bubbles, her bubbly personality, or Bubbles from The Powerpuff Girls. Notably, her house contains a Tom Nook photo, which is a rare item. Her initial phrase could be a reference to both her species and to people who \"have done things before they were cool\" \n." + "\n" + "She has the fashion hobby.");
            bubbles.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/a/a1/HDBubblesNL.png/revision/latest?cb=20200618183250");
            Character cheri = new Character("Cheri", "Female", "Peppy", "Cub", "March 17th", "GO! GO! GO, tralala!", "Cheri (アセロラ, Aserora, Acerola) is a peppy cub villager from the Animal Crossing series, making appearances in Animal Crossing and New Leaf. Her name is based off the word \"cherry,\" which defines her personality and is her color. Her initial catchphrase is a reference to her personality, as it makes her seem light-hearted and cheerful when she speaks. Her English name is related to the fruit cherry. Her birthday is on Shamrock Day. She appeared in the early games of the series, was absent in Wild World and City Folk, and returned in New Leaf. \n" + "\n" + "She appears on the album covers for I Love You and K.K. Faire.\n" + "\n" + "She has the fashion hobby.");
            cheri.setPicture("https://dodo.ac/np/images/thumb/4/4b/Cheri_NLa.png/200px-Cheri_NLa.png");
            Character cookie = new Character("Cookie", "Female", "Peppy", "Dog", "June 18th", "You know why I'm carrying this shovel around? It's to find fossils so I can look smart, arfer.", "Cookie (ペリーヌ Perīnu) is a peppy dog villager in the Animal Crossing series. She was absent from Wild World, but returned in City Folk. She is likely named Cookie because of her cute appearance and sweet personality or because treats for dogs are sometimes called cookies. Her initial catchphrase, \"arfer\", is a variation of the word \"arf\", the sound a dog makes.\n" + "\n" + "She appears on the album cover for DJ K.K., which is also her favorite song. \n " + "\n" + "She has the fashion hobby.");
            cookie.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/d/dd/CookieNH.png/revision/latest?cb=20200618151442");
            Character tangy = new Character("Tangy", "Female", "Peppy", "Cat", "June 17th", "They say cats hate citrus. THAT REALLY HURTS MY FEELINGS!", "Tangy (ヒャクパー, Hyakupā) is a peppy cat villager that appears in every game of the Animal Crossing series, except for Pocket Camp. The name \"Tangy\" comes from the sharp taste of citrus fruit. Her Japanese name is a contraction of \"100 Percent\" and refers to juice concentrate. \n " + "\n" + "She appears on the album cover for K.K. Birthday. \n " + "\n" + "She has the music hobby.");
            tangy.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/6/6b/D1225F44-54F1-482D-8AA9-E6076062616F.jpeg/revision/latest/scale-to-width-down/333?cb=20200616050659");
            Character maddie = new Character("Maddie", "Female", "Peppy", "Dog", "January 11th", "The IT revolution is under way.", "Maddie (マロン, Maron, Malon) is a peppy dog villager. Her initial phrase references her peppy personality, as \"yippee\" is used to express excitement. Maddie originally only appeared in the early games of the series, but she returned in Happy Home Designer as limited DLC, unlocking the Campus Set. She was first available from February 1st, 2016 to February 29th, 2016, and later again from May 2nd, 2016 to May 31st, 2016.\n" + "\n" + "Maddie returned to the series in New Leaf, as part of the Welcome amiibo update. By scanning amiibo cards, this villager can be met via the campground and invited to the town.\n" + "\n" + "She has the play hobby.");
            maddie.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/5/52/Maddie_HD.png/revision/latest/scale-to-width-down/350?cb=20180518161841");

            //jock
            Character dom = new Character("Dom", "Male", "Jock", "Sheep", "March 18th", "Be true to your most shiny self.", "Dom (ちゃちゃまる, Chachamaru, Chachamaru) is a jock sheep villager introduced in New Horizons, and later Pocket Camp. His Japanese catchphrase is \"funfun\" which can be translated as \"uh-huh\" or the onomatopoeic word \"sniff-sniff\". This could be a reference to his always sad expression. \n " + "He has the play hobby.");
            dom.setPicture("https://dodo.ac/np/images/thumb/7/75/Dom_NH.png/200px-Dom_NH.png");
            Character genji = new Character("Genji", "Male", "Jock", "Rabbit", "January 21st", "Fall down seven times, get up eight.", "Genji (ゲンジ, Genji) is a jock rabbit villager in the Animal Crossing series. He retains his name from the Japanese version, and both reference the titular character of The Tale of Genji by Murasaki Shikibu, which is considered by some to be the world's first novel. His initial phrase prior to New Horizons, \"otaku,\" is a formal second-person pronoun in Japanese; it can also refer to someone with an obsessive personality, which reflects on jock villagers' fitness and health obsessions. In New Horizons, his new initial phrase, \"mochi,\" refers to a type of rice cake.\n" + "\n" + "He has the fitness hobby.");
            genji.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/6/67/Genji_NH.png/revision/latest/scale-to-width-down/252?cb=20200322125429");
            Character kevin = new Character("Kevin", "Male", "Jock", "Pig", "April 26th", "Sometimes it's OK to get dirty.", "Kevin (イノッチ Inocchi) is a jock pig villager who first appeared in New Leaf. His Japanese name comes from イノシシ (inoshisi), which means wild boar. His English name may be a reference to the American actor and singer, Kevin Bacon. He also appears on the album cover for K.K. Samba, which may lightly represent the fact that he is related to a singer (Kevin Bacon). His catchphrase, \"weeweewee,\" may be a reference to \"This Little Piggy,\" a children's nursery rhyme.\n" + "\n" + "He is featured on the cover of K.K. Samba and he has the play hobby.");
            kevin.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/7/71/Kevin_NH.png/revision/latest?cb=20200402024235");
            Character kody = new Character("Kody", "Male", "Jock", "Cub", "September 28th", "Hmmm... Let me sleep for a bit longer! Pleeease, Mommyyyy!", "Kody (アイダホ, Aidaho, Idaho) is a jock cub villager in the Animal Crossing series. He has appeared in every game so far. His name is based off the Kodiak Bear. His Wild World picture quote: \"Drop and give me twenty!\" reflects his jock personality. \n " + "\n" + "He has the fitness hobby.");
            kody.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/4/4d/Kody_NewLeaf_Official.png/revision/latest/scale-to-width-down/313?cb=20130721212358");
            Character roald = new Character("Roald", "Male", "Jock", "Penguin", "January 5th", "I'm not waddling! I'm working my glutes!", "Roald (ペンタ, Penta) is a jock penguin villager from the Animal Crossing series. He has appeared in every game so far. Roald's name could possibly come from Roald Amundsen, the first person to reach Antarctica, the natural habitat of Adelie penguins. His initial phrase is a reference to the cold, as words are usually a stutter in cold temperatures. It is quite similar to Cube's, Gwen's, and Aurora's. \n " + "\n" + "He has the fitness hobby.");
            roald.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/7/7e/ROALD_New_Horizons.png/revision/latest/scale-to-width-down/350?cb=20200224042135");
            Character stinky = new Character("Stinky", "Male", "Jock", "Cat", "August 17th", "If the mask fits, wear it!", "Stinky (アセクサ, Asekusa) is a male cat villager in the Animal Crossing series. He has a jock personality. His name may refer to his appearance, the characteristics of which are usually associated with poor hygiene - greyish-green fur and a \"wrestling mask\" made of underwear over his face. His Japanese name is a combination of the words, \"sweat\" and \"stinky,\" which also enforces this idea. His initial phrase, \"GAHHHH\", may be a sound of strength and power, possibly referring to something to do with wrestling. Stinky was absent in Wild World, but he reappears in City Folk, New Leaf and New Horizons. \n " + "\n" + "He has the fitness hobby.");
            stinky.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/4/43/Stinky-1-.png/revision/latest?cb=20200417130345");
            Character rudy = new Character("Rudy", "Male", "Jock", "Cat", "December 20th", "Oooh, imagine that, a flea sucking the carbs right out of me!", "Rudy (チャス, Chasu) is a jock cat villager that first appeared in New Leaf. His English name may refer to Rudolph the Red-Nosed Reindeer, who has a red nose like Rudy. His initial phrase and his birthday support this possibility. His New Leaf picture quote is a reference to how cats land on their feet. \n " + "\n" + "He has the play hobby.");
            rudy.setPicture("https://vignette.wikia.nocookie.net/animalcrossing/images/3/35/Rudy_HD.png/revision/latest/scale-to-width-down/350?cb=20180917123841");

            //            Data.getData().clearCharacterList();

//            Data.getData().clearAccountList();

            Account mokko = new Account("mokko", "melanie123");
            Account test1 = new Account("test", "testing1");

            Account admin = new Account("admin", "admintest");
            Account.setAdministrator(admin);

            Material softwood = new Material ("Soft wood");
            Material treebranch = new Material("Tree branch");
            Material clay = new Material("Clay");
            Material goldnugget = new Material("Gold nugget");
            Material ironnugget = new Material("Iron nugget");
            Material wood = new Material("Wood");
            Material hardwood = new Material("Hard wood");
            Material stone = new Material("Stone");
            Material clumpofweeds = new Material("Clump of weeds");
            Material starfragment = new Material("Star fragment");

        } catch (IOException | ClassNotFoundException e) {
            e.printStackTrace();
        }
    }

    public void contextDestroyed(ServletContextEvent sce) {
        System.out.println("System is shutting down");
        Schedulers.shutdownNow();
        HttpResources.disposeLoopsAndConnectionsLater(Duration.ZERO, Duration.ZERO).block();
        try {
            PersistenceManager.saveDataToAzure();
            System.out.println("Saved");

        } catch (IOException e) {
            e.printStackTrace();
        }
    }

}


